version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aviation_postgres
    environment:
      POSTGRES_DB: aviation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aviation_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: aviation_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aviation_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: aviation_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - aviation_network
    depends_on:
      - redis

networks:
  aviation_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: